## **NUMPY**


**Importance of Numpy**

NumPy is needed because it provides fast, memory-efficient numerical computations. It supports multi-dimensional arrays, easy mathematical operations, and is the foundation of Data Science, Machine Learning, and Scientific Computing.

**Applications of NumPy**

1. **Data Analysis** – Processing and analyzing large datasets.
2. **Machine Learning** – Handling numerical data for AI and ML models.
3. **Scientific Computing** – Performing complex mathematical calculations.
4. **Image Processing** – Representing and manipulating images as arrays.
5. **Data Visualization** – Preparing data for plotting with libraries like Matplotlib.
6. **Matrix Operations** – Solving matrix and linear algebra problems.


# **Import NumPy**

In [1]:
# Import the NumPy library and give it the short name 'np'
import numpy as np

# **Creating Arrays**

In [2]:
# Create a NumPy array from a Python list
arr = np.array([10, 20, 30, 40])
print(arr)


# Create numbers from 1 to 10 (10 is not included)
arr = np.arange(1, 11)
print(arr)


# Create 5 equally spaced numbers between 1 and 10
arr = np.linspace(1, 10, 5)
print(arr)


# Create a 2x3 array filled with zeros
arr = np.zeros((2, 3))
print(arr)


# Create a 3x2 array filled with ones
arr = np.ones((3, 2))
print(arr)


# Create a 3x3 identity matrix
# (Diagonal elements are 1, all others are 0)
arr = np.eye(3)
print(arr)


# Create a 2x3 array where every element is 7
arr = np.full((2, 3), 7)
print(arr)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7 7]
 [7 7 7]]


# **Array Information**

In [3]:
# Create a 2D array
arr = np.array([[1,2],[3,4]])


# Find how many dimensions the array has
print(arr.ndim)


# Find the number of rows and columns
print(arr.shape)


# Find the total number of elements
print(arr.size)


# Find the data type of elements
print(arr.dtype)


# Find the memory used by one element (in bytes)
print(arr.itemsize)

2
(2, 2)
4
int64
8


# **Indexing & Slicing**

In [7]:
# Create an array
arr = np.array([10,20,30,40])


#Indexing
# Get the element at index 2
print(arr[2])


#Slicing
# Get elements from index 1 to index 2
print(arr[1:3])


#Boolean Indexing
# Get elements greater than 20
print(arr[arr > 20])


#Fancy Indexing
# Get elements at index 0 and 2
print(arr[[0,2]])


30
[20 30]
[30 40]
[10 30]


# **Mathematical Operations**

In [5]:
# Import NumPy
import numpy as np

# Create two arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# Display the arrays
print("Array A:", a)
print("Array B:", b)

Array A: [10 20 30]
Array B: [1 2 3]


In [6]:
# Add corresponding elements of two arrays
result = a + b

# Display the result
print("Addition:", result)

# OR
print(np.add(a, b))


# Subtract elements of array B from array A
result = a - b

print("Subtraction:", result)

# OR
print(np.subtract(a, b))

# Multiply corresponding elements
result = a * b

print("Multiplication:", result)

# OR
print(np.multiply(a, b))


# Divide elements of array A by array B
result = a / b

print("Division:", result)

# OR
print(np.divide(a, b))

Addition: [11 22 33]
[11 22 33]
Subtraction: [ 9 18 27]
[ 9 18 27]
Multiplication: [10 40 90]
[10 40 90]
Division: [10. 10. 10.]
[10. 10. 10.]
