<a href="https://colab.research.google.com/github/venayack-paatil/Python-Libraries/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch**
**Definition**

PyTorch is an open-source Deep Learning framework developed by Meta (Facebook). It is used to build, train, and deploy Artificial Intelligence and Deep Learning models.

# **Importance of PyTorch**
* Beginner Friendly
* Dynamic Computation Graph
* Fast GPU Computation
* Industry Standard
* Widely used in AI Research
* Easy Debugging

# **Applications of PyTorch**
* Image Classification
* Object Detection
* Natural Language Processing (NLP)
* Chatbots
* Recommendation Systems
* Medical Image Analysis
* Autonomous Vehicles
* Generative AI (LLMs, Diffusion Models)

# **Import PyTorch**

In [1]:
# Import PyTorch library
import torch

# Import Neural Network module
import torch.nn as nn

# Import Optimization module
import torch.optim as optim

# **Create Tensors**
**torch.tensor()**

In [2]:
# Create a tensor

tensor = torch.tensor([10,20,30,40])

print(tensor)

tensor([10, 20, 30, 40])


**torch.zeros()**

In [3]:
# Create a tensor filled with zeros

tensor = torch.zeros(2,3)

print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


**torch.ones()**

In [4]:
# Create a tensor filled with ones

tensor = torch.ones(2,3)

print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


**torch.rand()**

In [5]:
# Create a tensor with random values

tensor = torch.rand(2,3)

print(tensor)

tensor([[0.2526, 0.6645, 0.8419],
        [0.5410, 0.1752, 0.8721]])


**torch.randn()**

In [6]:
# Create a tensor with random values

tensor = torch.rand(2,3)

print(tensor)

tensor([[0.6247, 0.7184, 0.0418],
        [0.1617, 0.2023, 0.4820]])


# **Tensor Information**
**shape**

In [7]:
# Display tensor shape

print(tensor.shape)

torch.Size([2, 3])


**dtype**

In [8]:
# Display tensor data type

print(tensor.dtype)

torch.float32


**ndim**

In [9]:
# Display number of dimensions

print(tensor.ndim)

2


**size()**

In [10]:
# Display tensor size

print(tensor.size())

torch.Size([2, 3])


# **Tensor Operations**
**Addition**

In [11]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a+b)

tensor([5, 7, 9])


**Subtraction**

In [12]:
print(a-b)

tensor([-3, -3, -3])


**Multiplication**

In [13]:
print(a*b)

tensor([ 4, 10, 18])


**Division**

In [14]:
print(a/b)

tensor([0.2500, 0.4000, 0.5000])


**Matrix Multiplication**

In [15]:
A = torch.tensor([[1,2],[3,4]])

B = torch.tensor([[5,6],[7,8]])

print(torch.matmul(A,B))

tensor([[19, 22],
        [43, 50]])


# **Reshaping Tensors**
**reshape()**

In [16]:
tensor = torch.arange(12)

print(tensor.reshape(3,4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


**view()**

In [17]:
tensor = torch.arange(12)

print(tensor.view(4,3))

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


**squeeze()**

In [18]:
tensor = torch.rand(1,3,1)

print(tensor.squeeze())

tensor([0.3935, 0.8458, 0.6590])


**unsqueeze()**

In [19]:
tensor = torch.tensor([1,2,3])

print(tensor.unsqueeze(0))

tensor([[1, 2, 3]])


# **GPU**
**cuda()**

In [20]:
# Check GPU availability

print(torch.cuda.is_available())

False


In [21]:
# Move tensor to GPU

tensor = torch.tensor([1,2,3])

if torch.cuda.is_available():
    tensor = tensor.cuda()

print(tensor)

tensor([1, 2, 3])


# **Automatic Differentiation**
**requires_grad**

In [23]:
x = torch.tensor(2.0,requires_grad=True)

print(x)

tensor(2., requires_grad=True)


**backward()**

In [24]:
y = x**2

y.backward()

print(x.grad)

tensor(4.)


# **Neural Networks**
**nn.Linear()**

In [25]:
model = nn.Linear(2,1)

print(model)

Linear(in_features=2, out_features=1, bias=True)


**nn.ReLU()**

In [26]:
relu = nn.ReLU()

x = torch.tensor([-1.0,0.0,2.0])

print(relu(x))

tensor([0., 0., 2.])


**nn.Sequential()**

In [27]:
model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)


# **Loss Functions**
**nn.MSELoss()**

In [28]:
loss_function = nn.MSELoss()

print(loss_function)

MSELoss()


**nn.CrossEntropyLoss()**

In [29]:
loss_function = nn.CrossEntropyLoss()

print(loss_function)

CrossEntropyLoss()


# **Optimizers**
**SGD**

In [30]:
optimizer = optim.SGD(
    model.parameters(),
    lr=0.01
)

print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


**Adam**

In [31]:
optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)


# **Training Loop**

In [33]:
# Forward Pass

output = model(torch.rand(1,2))

# Calculate Loss

loss = nn.MSELoss()(output,torch.rand(1,1))

# Clear previous gradients

optimizer.zero_grad()

# Backpropagation

loss.backward()

# Update weights

optimizer.step()

# **Save Model**
**torch.save()**

In [35]:
torch.save(model.state_dict(),"model.pth")

**torch.load(**)

In [36]:
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>