<a href="https://colab.research.google.com/github/venayack-paatil/Python-Libraries/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TensorFlow**
**Definition**

TensorFlow is an open-source Deep Learning library developed by Google. It is used to build, train, and deploy Artificial Intelligence and Deep Learning models.

# **Importance of TensorFlow**
* Developed by Google
* Supports CPUs, GPUs, and TPUs
* Beginner-friendly using Keras API
* Industry-standard Deep Learning library
* Used in AI research and production

# **Applications**
* Image Classification
* Face Recognition
* Object Detection
* Chatbots
* Language Translation
* Stock Price Prediction
* Medical Diagnosis
* Self-driving Cars

# **Installation**

In [1]:
# Install TensorFlow

!pip install tensorflow

# **Import TensorFlow**

In [2]:
# Import TensorFlow library

import tensorflow as tf

# Import NumPy

import numpy as np

# Import Matplotlib

import matplotlib.pyplot as plt

# **Check TensorFlow Version**
**Function**

tf.__version__

In [3]:
# Display TensorFlow version

print(tf.__version__)

2.20.0


# **Create Tensor**
**Function**

tf.constant()

In [4]:
# Create a constant tensor

tensor = tf.constant([10,20,30,40])

print(tensor)

tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)


# **Create Variables**
**Function**

tf.Variable()

In [5]:
# Create a variable tensor

variable = tf.Variable([1,2,3])

print(variable)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


# **Tensor Shape**
**Function**

tf.shape()

In [6]:
# Display tensor shape

tensor = tf.constant([[1,2],[3,4]])

print(tf.shape(tensor))

tf.Tensor([2 2], shape=(2,), dtype=int32)


# **Tensor Operations**
**Functions**

tf.add()

tf.subtract()

tf.multiply()

tf.divide()

In [7]:
# Create tensors

a = tf.constant([10,20])

b = tf.constant([5,2])

print(tf.add(a,b))

print(tf.subtract(a,b))

print(tf.multiply(a,b))

print(tf.divide(a,b))

tf.Tensor([15 22], shape=(2,), dtype=int32)
tf.Tensor([ 5 18], shape=(2,), dtype=int32)
tf.Tensor([50 40], shape=(2,), dtype=int32)
tf.Tensor([ 2. 10.], shape=(2,), dtype=float64)


# **Random Tensor**
**Function**

tf.random.normal()

In [8]:
# Create random tensor

tensor = tf.random.normal(shape=(2,3))

print(tensor)

tf.Tensor(
[[-2.5229983  -0.9865986  -0.39643598]
 [ 1.9311217   0.80085355 -0.1904419 ]], shape=(2, 3), dtype=float32)


# **Sequential Model**
**Function**

tf.keras.Sequential()

In [16]:
# Create neural network

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.Input(shape=(1,)),
    tf.keras.layers.Dense(8, activation="relu"),
    tf.keras.layers.Dense(1)
])

print(model)

<Sequential name=sequential_4, built=True>


# **Compile Model**
**Function**

compile()

In [17]:
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

# **Train Model**
**Function**

fit()

In [18]:
import numpy as np

X = np.array([[1], [2], [3], [4], [5]], dtype=np.float32)
y = np.array([[2], [4], [6], [8], [10]], dtype=np.float32)

model.fit(X, y, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 942ms/step - loss: 42.7582 - mae: 5.9147
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 42.5436 - mae: 5.8994
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 42.3295 - mae: 5.8840
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 42.1161 - mae: 5.8686
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 41.9032 - mae: 5.8533
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 41.6908 - mae: 5.8379
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 41.4791 - mae: 5.8225
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 41.2680 - mae: 5.8072
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 41.0575 - mae: 5.7918
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 40.8476 - mae: 5.7765
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 40.6383 - mae: 5.7612
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 40.4297 - mae: 5.7458
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/ste

# **Predict**
**Function**

predict()

In [19]:
# Predict output

prediction = model.predict(np.array([6]))

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step
[[1.5467403]]


# **Evaluate Model**
**Function**

evaluate()

In [20]:
# Evaluate model

model.evaluate(X,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 32.8345 - mae: 5.1578


[32.83445358276367, 5.157802581787109]

# **Save Model**
**Function**

save()

In [21]:
# Save trained model

model.save("model.keras")

# **Load Model**
**Function**

load_model()

In [22]:
# Load saved model

loaded_model = tf.keras.models.load_model("model.keras")

print(loaded_model)

<Sequential name=sequential_4, built=True>


# **MNIST Dataset**
**Function**

tf.keras.datasets.mnist.load_data()

In [23]:
# Load MNIST dataset

(X_train,y_train),(X_test,y_test)=tf.keras.datasets.mnist.load_data()

print(X_train.shape)

print(y_train.shape)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
(60000, 28, 28)
(60000,)


# **Dense Layer**
**Function**

Dense()

In [24]:
# Create Dense layer

layer = tf.keras.layers.Dense(
    units=64,
    activation="relu"
)

print(layer)

<Dense name=dense_10, built=False>


# **Dropout Layer**
**Function**

Dropout()

In [26]:
# Create Dropout layer

layer = tf.keras.layers.Dropout(0.3)

print(layer)

<Dropout name=dropout, built=True>


# **Flatten Layer**
**Function**

Flatten()

In [27]:
# Flatten image

layer = tf.keras.layers.Flatten()

print(layer)

<Flatten name=flatten, built=False>


# **Convolution Layer**
**Function**

Conv2D()

In [28]:
# Create convolution layer

layer = tf.keras.layers.Conv2D(
    filters=32,
    kernel_size=(3,3),
    activation="relu"
)

print(layer)

<Conv2D name=conv2d, built=False>


# **Max Pooling**
**Function**

MaxPooling2D()

In [29]:
# Create pooling layer

layer = tf.keras.layers.MaxPooling2D(
    pool_size=(2,2)
)

print(layer)

<MaxPooling2D name=max_pooling2d, built=True>


# **TensorBoard**
**Function**

TensorBoard()

In [30]:
# Create TensorBoard callback

callback = tf.keras.callbacks.TensorBoard(
    log_dir="logs"
)

print(callback)

# **Summary of Model**
**Function**

summary()

In [31]:
# Display model summary

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 8)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 77 (312.00 B)

 Trainable params: 25 (100.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 52 (212.00 B)